### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by BadSide84** [Dutch-Drone-Racing/RH-Plugin-Overlays#1]
Hi Jesse

Intalled the plugin and also R v4.2.0 beta 1, plugin loaded but i can see this:

On the settings page of your RotorHazard panel the section DDR - OBS Overlays shows up. Press the link, it will bring you to the page with links to the overlays.

**Comment by JesseFPV** [comment]
This function is currently only on MAIN RotorHazard branch as the function for Markup on the settings screen is not yet in the beta. I expect it will be available on the next beta release. For now you can directly go to `[your_rotorhazard_address]/ddr_overlays `. I will add it to the docs.
